server:
  port: 8001

feign:
  client:
    config:
      feignName:
        connectionTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: eureka-collection-client-8001
    prefer-ip-address: true #显示ip地址

info:
  app.name: weather-microservice
  company.name: com.company.project
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
spring:
  application:
    name: eureka-collection-client