server:
  port: 3344


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: config-server-3344
    prefer-ip-address: true #显示ip地址

info:
  app.name: weather-microservice
  company.name: com.company.project
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
spring:
  application:
    name: config-server-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:maxmarvel/cloudProject.git
          search-paths: config/cloud-weather   #文件目录
