server:
  port: 8003


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: eureka-report-client-8003
    prefer-ip-address: true #显示ip地址

info:
  app.name: weather-microservice
  company.name: com.company.project
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
spring:
  application:
    name: eureka-report-client