server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: zuul-gateway-9527
    prefer-ip-address: true #显示ip地址

info:
  app.name: weather-microservice
  company.name: com.company.project
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    city.serviceId: EUREKA-CITY-CLIENT
    city.path: /city/**
    data.serviceId: EUREKA-DATA-CLIENT
    data.path: /data/**