spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: config-client
eureka:
  client:
    service-url:
      defaultZone: http://eurek7001.com:7001/eureka/

info:
  app.name: project-cloud
  company.name: com.company.project
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8202
spring:
  profiles: test
  application: config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/